#!/bin/bash -e

sudo iptables -t nat -I OUTPUT -p tcp -o lo --dport 443 -j REDIRECT --to-ports 8443
sudo iptables -t nat -I OUTPUT -p tcp -o lo --dport 80 -j REDIRECT --to-ports 8080
sudo apt-get install  iptables-persistent
sudo sh -c "iptables-save > /etc/iptables/rules.v4"
